FROM alpine:latest

ARG RELEASE_TAG

RUN apk add gettext wireguard-tools caddy

COPY client-entrypoint.sh /usr/bin/client-entrypoint.sh

COPY ./minecraft-server/nginx/minecraft.conf /etc/nginx/stream.conf

ENV NOTEWORTHY_ENV $RELEASE_TAG
ENV LINK_MTU=1380

ENTRYPOINT [ "client-entrypoint.sh" ]
